version: '3.8'

services:
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env
    expose:
      - 3306
  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env
    expose:
      - 9000
  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/data/db
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/data/wp

networks:
  inception:
    driver: bridge
